@'
title: Jin Lu
author: Jin Lu
email: jin.lu@uga.edu
description: Assistant Professor at the University of Georgia working on machine learning, optimization, efficient foundation models, and trustworthy AI.
url: "https://jinlucs.github.io"
baseurl: ""

navbar-links:
  Home: "https://jinlucs.github.io/"
  Research: "research"
  Group: "group"
  Teaching: "teaching"
  Papers: "papers"
  ArXiv Digest: "arxiv"
  CV: "/assets/files/cv.pdf"
  About: "about"

avatar: "/assets/img/photo_small_jin.jpg"
round-avatar: true

social-network-links:
  email: "jin.lu@uga.edu"
  github: jinlucs
  google-scholar: citations?user=FK_W-KIAAAAJ&hl

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

navbar-col: "#BA0C2F"
navbar-text-col: "#FFFFFF"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#999E57"
hover-col: "#0085A1"
footer-col: "#BA0C2F"
footer-text-col: "#FFFFFF"
footer-link-col: "#FFFFFF"

site-css:
  - "/assets/css/custom-styles.css"

timezone: "America/New_York"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-spaceship
'@ | Set-Content -Path .\_config.yml -Encoding UTF8